### ISSUE TITLE
ToDo Twit Mock

### ISSUE THREAD

**Issue by GoesToEleven** [GoesToEleven/SummerBootCamp#1]
- [x] logout button needs to show up when user is logged in
- [x] tweet button needs to show up when user is logged in
- [x] add @user to profile.html page
- [x] post tweets
- [x] show tweets on home.html
- [x] show @user filtered tweets on profile.html page
- [x] tweet should clear from modal after modal is closed

**Comment by GoesToEleven** [comment]
- [ ] add time to tweets
- [ ] format display of tweets

**Comment by GoesToEleven** [comment]
Finished all of my issues for today
